<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_revenue extends CI_Model
{

    public $table = 't_revenue';
    public $id = 'id_revenue';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_revenue,judul,revenue,month,download,renew,campaign,r.status');
        $this->datatables->from('t_revenue r');
		$this->datatables->join('t_rbt t','t.id_rbt=r.id_rbt','inner');
        //add this line for join
        //$this->datatables->join('table2', 't_revenue.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('c_revenue/update/$1'),'<i class="fa fa-edit"></i>', 'class="btn btn-xs btn-warning" data-toggle="tooltip" title="Edit"')."  ".anchor(site_url('c_revenue/delete/$1'),'<i class="fa fa-trash"></i>', 'class="btn btn-xs btn-danger" onclick="return confirmdelete(\'c_revenue/delete/$1\')" data-toggle="tooltip" title="Delete"'), 'id_revenue');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        //$this->db->order_by($this->id, $this->order);
        //return $this->db->get($this->table)->result();
        $this->db->select('id_revenue,judul,revenue,month,download,renew,campaign,r.status');
        $this->db->from('t_revenue r');
        $this->db->join('t_rbt t','t.id_rbt=r.id_rbt','inner');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_revenue', $q);
	$this->db->or_like('id_rbt', $q);
	$this->db->or_like('revenue', $q);
	$this->db->or_like('month', $q);
	$this->db->or_like('download', $q);
	$this->db->or_like('renew', $q);
	$this->db->or_like('campaign', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_revenue', $q);
	$this->db->or_like('id_rbt', $q);
	$this->db->or_like('revenue', $q);
	$this->db->or_like('month', $q);
	$this->db->or_like('download', $q);
	$this->db->or_like('renew', $q);
	$this->db->or_like('campaign', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }


}

/* End of file M_revenue.php */
/* Location: ./application/models/M_revenue.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-03 12:36:45 */
/* http://harviacode.com */